export type ProductStatus = "completed" | "in-progress" | "planned";
export type ProductCategory =
  | "sales"
  | "marketing"
  | "agent"
  | "creative"
  | "data"
  | "dev";

export interface Product {
  id: string;
  index: number;
  name: string;
  positioning: string;
  url: string;
  access: string;
  owner?: string;
  status: ProductStatus;
  category: ProductCategory;
  note?: string;
  reportPath?: string;
}

export const CATEGORY_LABEL: Record<ProductCategory, string> = {
  sales: "销售",
  marketing: "营销",
  agent: "Agent 协作",
  creative: "创意生成",
  data: "数据分析",
  dev: "AI 开发",
};

export const STATUS_LABEL: Record<ProductStatus, string> = {
  completed: "已完成",
  "in-progress": "进行中",
  planned: "计划中",
};

export const products: Product[] = [
  {
    id: "artisan",
    index: 1,
    name: "Artisan AI",
    positioning: "AI 销售员工（AI BDR）",
    url: "https://www.artisan.co/",
    access: "企业邮箱",
    owner: "倩倩",
    status: "completed",
    category: "sales",
    reportPath: "artisan-co",
  },
  {
    id: "kuse",
    index: 2,
    name: "Kuse",
    positioning: "AI GTM / AI Sales Automation",
    url: "https://www.kuse.ai/",
    access: "开放",
    owner: "倩倩",
    status: "completed",
    category: "agent",
    reportPath: "kuse-ai",
  },
  {
    id: "junior",
    index: 3,
    name: "Junior AI",
    positioning: "AI 数字员工 / 协作型 Agent",
    url: "https://junior.so/",
    access: "不完全开放",
    status: "completed",
    category: "agent",
    note: "与 Kuse 同公司：Kuse 是系统，Junior 是人格化 AI 员工",
    reportPath: "junior-so",
  },
  {
    id: "okara",
    index: 4,
    name: "Okara AI",
    positioning: "AI Marketing Agent Suite",
    url: "https://okara.ai/",
    access: "开放",
    owner: "倩倩",
    status: "in-progress",
    category: "marketing",
    reportPath: "okara-ai",
  },
  {
    id: "moxt",
    index: 5,
    name: "Moxt",
    positioning: "AI 客户互动 / AI 协作",
    url: "https://moxt.ai/zh-CN",
    access: "免费开放",
    owner: "倩倩",
    status: "completed",
    category: "agent",
    reportPath: "moxt-ai",
  },
  {
    id: "monday",
    index: 6,
    name: "Monday",
    positioning: "企业协作 + AI Workflow 平台",
    url: "https://monday.com/w/agents",
    access: "开放",
    owner: "何龙",
    status: "completed",
    category: "agent",
    reportPath: "monday-agents",
  },
  {
    id: "jasper",
    index: 7,
    name: "Jasper",
    positioning: "AI 营销内容平台",
    url: "https://www.jasper.ai/",
    access: "开放",
    owner: "何龙",
    status: "completed",
    category: "marketing",
    reportPath: "jasper-ai",
  },
  {
    id: "pika",
    index: 8,
    name: "Pika Labs",
    positioning: "AI 视频生成",
    url: "https://pika.art/",
    access: "开放",
    owner: "何龙",
    status: "completed",
    category: "creative",
    reportPath: "pika-me",
  },
  {
    id: "relevance",
    index: 9,
    name: "Relevance AI",
    positioning: "通用 Multi-Agent AI 平台",
    url: "https://relevanceai.com/",
    access: "有免费版",
    owner: "何龙",
    status: "completed",
    category: "agent",
    reportPath: "relevanceai-com",
  },
  {
    id: "kaito",
    index: 10,
    name: "Kaito",
    positioning: "Crypto 信息分析平台",
    url: "https://kaito.ai/",
    access: "部分免费",
    owner: "何龙",
    status: "completed",
    category: "data",
    reportPath: "kaito-ai",
  },
  {
    id: "serus",
    index: 11,
    name: "Serus",
    positioning: "AI Agent / 企业自动化",
    url: "https://www.serus.io/",
    access: "联系销售",
    owner: "何龙",
    status: "completed",
    category: "agent",
    reportPath: "serus-io",
  },
  {
    id: "11x",
    index: 12,
    name: "11x",
    positioning: "AI 销售员工（AI SDR / AI 电话销售）",
    url: "https://www.11x.ai/",
    access: "联系销售",
    owner: "何龙",
    status: "completed",
    category: "sales",
    reportPath: "11x-ai",
  },
  {
    id: "lunar-strategy",
    index: 13,
    name: "Lunar Strategy",
    positioning: "Web3 营销代理公司",
    url: "https://www.lunarstrategy.com/",
    access: "联系销售",
    owner: "何龙",
    status: "completed",
    category: "marketing",
    reportPath: "lunarstrategy-com",
  },
  {
    id: "onesight",
    index: 14,
    name: "OneSight",
    positioning: "海外社媒管理工具",
    url: "https://onesight.com/",
    access: "申请体验",
    owner: "何龙",
    status: "completed",
    category: "marketing",
    reportPath: "onesight-com",
  },
  {
    id: "octok",
    index: 15,
    name: "Octok",
    positioning: "AI 出海团队 / Global Expansion Team Platform",
    url: "https://www.octok.com/",
    access: "邀请制",
    status: "completed",
    category: "agent",
    note: "6 个具名 AI 角色(Navigator/Alice/Sophia/William/Daniel/Ethan)对应出海公司组织架构",
    reportPath: "octok-com",
  },
  {
    id: "theaicmo",
    index: 16,
    name: "The AI CMO",
    positioning: "AI 营销 Agent / 自主跑 Campaign",
    url: "https://theaicmo.com/",
    access: "注册即用",
    status: "completed",
    category: "marketing",
    note: "plans strategy → writes assets → publishes → learns,定位 agent 而非 prompt 工具",
    reportPath: "theaicmo-com",
  },
  {
    id: "qoder",
    index: 17,
    name: "Qoder",
    positioning: "阿里:从 AI IDE 升级为智能体自主开发工作台",
    url: "https://qoder.com/",
    access: "—",
    status: "planned",
    category: "dev",
  },
  {
    id: "miaoda",
    index: 18,
    name: "秒哒",
    positioning: "百度:无代码开发平台,「一句话做应用」",
    url: "https://www.miaoda.cn/",
    access: "—",
    status: "planned",
    category: "dev",
  },
  {
    id: "dumate",
    index: 19,
    name: "DuMate",
    positioning: "百度:统一通用智能体入口,集成百度核心 AI 能力",
    url: "https://www.dumate.cn/app",
    access: "—",
    status: "planned",
    category: "agent",
  },
  {
    id: "qclaw",
    index: 20,
    name: "QClaw",
    positioning: "腾讯:AI 智能体部署工具",
    url: "https://qclaw.qq.com/",
    access: "—",
    status: "planned",
    category: "dev",
  },
  {
    id: "workbuddy",
    index: 21,
    name: "WorkBuddy",
    positioning: "腾讯:生产力 AI 代理服务",
    url: "https://www.codebuddy.cn/work/",
    access: "—",
    status: "planned",
    category: "agent",
  },
  {
    id: "marvis",
    index: 22,
    name: "Marvis",
    positioning: "腾讯:6 个 Agent 组成的协作体系,7×24 小时在线",
    url: "https://marvis.qq.com/",
    access: "—",
    status: "planned",
    category: "agent",
  },
  {
    id: "fin",
    index: 23,
    name: "Fin AI",
    positioning: "AI 客服 Agent(Intercom 旗下),按 Resolution 结果计费",
    url: "https://fin.ai/",
    access: "—",
    status: "planned",
    category: "agent",
    note: "客服赛道头部 Autopilot,$0.99/单,不计 token / 不计对话",
  },
  {
    id: "dust",
    index: 24,
    name: "Dust",
    positioning: "企业级 AI Agent 平台,连接公司知识与工具(Sales/Support/Ops/Marketing)",
    url: "https://dust.tt/",
    access: "—",
    status: "planned",
    category: "agent",
  },
];

export const stats = {
  total: products.length,
  completed: products.filter((p) => p.status === "completed").length,
  inProgress: products.filter((p) => p.status === "in-progress").length,
};
